### ISSUE TITLE
Enumerating users returns error

### ISSUE THREAD

**Issue by brammittendorff-dd** [m4ll0k/WPSeku#28]
By using the command `python3 wpseku.py -u `:

``` 
[ i ] Enumerating users...
Traceback (most recent call last):
  File "wpseku.py", line 79, in <module>
    wpseku().main()
  File "wpseku.py", line 73, in main
    wpusers(self.url,None,self.kwargs).run()
  File "/wpseku/modules/discovery/users/wpusers.py", line 25, in run
    users  = self.wpjson()
  File "/wpseku/modules/discovery/users/wpusers.py", line 54, in wpjson
    json = loads(resp.content,encoding="utf-8")
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

**Comment by Redshoee** [comment]
same error,

[ i ] Enumerating users...
Traceback (most recent call last):
  File "wpseku.py", line 71, in <module>
    wpseku().main()
  File "wpseku.py", line 65, in main
    wpusers(self.url,None,self.kwargs).run()
  File "/home/r/wpseku/modules/discovery/users/wpusers.py", line 20, in run
    users = self.wpjson()
  File "/home/r/wpseku/modules/discovery/users/wpusers.py", line 50, in wpjson
    json = loads(resp.content, encoding="utf-8")
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'


python3 --version
Python 3.5.2

**Comment by Redshoee** [comment]
same error,

[ i ] Enumerating users...
Traceback (most recent call last):
File "wpseku.py", line 71, in 
wpseku().main()
File "wpseku.py", line 65, in main
wpusers(self.url,None,self.kwargs).run()
File "/wpseku/modules/discovery/users/wpusers.py", line 20, in run
users = self.wpjson()
File "/wpseku/modules/discovery/users/wpusers.py", line 50, in wpjson
json = loads(resp.content, encoding="utf-8")
File "/usr/lib/python3.5/json/init.py", line 312, in loads
s.class.name))
TypeError: the JSON object must be str, not 'bytes'

python3 --version
Python 3.5.2
