### ISSUE TITLE
I run it ,found such error

### ISSUE THREAD

**Issue by gitscamI** [m4ll0k/WPSeku#30]
[ i ] Enumerating users...
Traceback (most recent call last):
  File "wpseku.py", line 79, in <module>
    wpseku().main()
  File "wpseku.py", line 73, in main
    wpusers(self.url,None,self.kwargs).run()
  File "/work/wpseku/wpseku/modules/discovery/users/wpusers.py", line 25, in run
    users  = self.wpjson()
  File "/work/wpseku/wpseku/modules/discovery/users/wpusers.py", line 54, in wpjson
    json = loads(resp.content,encoding="utf-8")
  File "/usr/lib64/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
[root@yellow wpseku]# the JSON object must be str, not 'bytes'

**Comment by fabaff** [comment]
Works fine for me on my test instance.

```bash
[ i ] Enumerating users...
--------------------------------
| ID | Username        | Login |
--------------------------------
|  0 | Test user       | test1 |
|  1 |                 | admin |
|  2 |                 | test  |
--------------------------------
```

Can you reproduce this error with every run?

**Comment by fabaff** [comment]
Duplicate of #28.
