### ISSUE TITLE
Can't run wpseku.py

### ISSUE THREAD

**Issue by SivaPrasad43** [m4ll0k/WPSeku#36]
terminate showing this when runnning python3 wpseku.py...plizz help!!!
Traceback (most recent call last):
  File "wpseku.py", line 5, in <module>
    from lib.scan import *
  File "/root/Desktop/WPSeku-master/lib/scan.py", line 13, in <module>
    from humanfriendly.tables import format_pretty_table
ModuleNotFoundError: No module named 'humanfriendly'

**Comment by professorkilo** [comment]
my similar issue:

Traceback (most recent call last):
  File "wpseku.py", line 10, in <module>
    from modules.bruteforce.wpxmlrpc import *
  File "/home/xxxxxxxx/wpseku/modules/bruteforce/wpxmlrpc.py", line 4, in <module>
    from lib.check import *
  File "/home/xxxxxxxx/wpseku/lib/check.py", line 8, in <module>
    from urllib.parse import urlparse
ImportError: No module named parse

**Comment by m4ll0k** [comment]
`pip3**** install humanfriendly`

**Comment by fabaff** [comment]
That's described in the [installation section](https://github.com/m4ll0k/WPSeku#installation).

```bash
pip3 install -r requirements.txt
```

**Comment by securiteinfo** [comment]
On debian : 
apt-get install python3-pip
pip3 install -r requirements.txt

**Comment by Sechunt3r** [comment]
Still Getting Error 

┌─[✗]─[root@parrot]─[/home/sechunt3r/Desktop/Tools/WPSeku]
└──╼ #python3 wpseku.py
Traceback (most recent call last):
  File "wpseku.py", line 4, in <module>
    from lib.scan import *
  File "/home/sechunt3r/Desktop/Tools/WPSeku/lib/scan.py", line 15, in <module>
    from humanfriendly.tables import format_pretty_table
ImportError: No module named 'humanfriendly'
┌─[✗]─[root@parrot]─[/home/sechunt3r/Desktop/Tools/WPSeku]
└──╼ #python wpseku.py
Traceback (most recent call last):
  File "wpseku.py", line 6, in <module>
    from modules.bruteforce.wpxmlrpc import *
  File "/home/sechunt3r/Desktop/Tools/WPSeku/modules/bruteforce/wpxmlrpc.py", line 10, in <module>
    from lib.request import *
  File "/home/sechunt3r/Desktop/Tools/WPSeku/lib/request.py", line 10, in <module>
    from lib.check import *
  File "/home/sechunt3r/Desktop/Tools/WPSeku/lib/check.py", line 7, in <module>
    from urllib.parse import urlparse
ImportError: No module named parse

**Comment by whybwi** [comment]
@mangkepweng 
python3 wpseku.py --url https://xxx --brute --user test --wordlist wl.txt --verbose

_Sent from my ZenFone 2 Laser (ZE500KG) using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Weapon-X6** [comment]
Still not working on Kali linux 2018

**Comment by thuva11** [comment]
Still, I am facing this error, Any suggestions

**Comment by ashvish183** [comment]
guys wpseku is used in windows
and u only need to read the readme.md file 
here are the instruction:-
## Installation
```
$ git clone https://github.com/m4ll0k/WPSeku.git wpseku
$ cd wpseku
$ pip3 install -r requirements.txt
$ python3 wpseku.py
```
## Usage
### Generic Scan

`python3 wpseku.py --url https://www.xxxxxxx.com --verbose`
