### ISSUE TITLE
Error in "Enumerating users"

### ISSUE THREAD

**Issue by securiteinfo** [m4ll0k/WPSeku#39]
[ i ] Enumerating users...
Traceback (most recent call last):
  File "wpseku.py", line 71, in <module>
    wpseku().main()
  File "wpseku.py", line 65, in main
    wpusers(self.url,None,self.kwargs).run()
  File "/root/WPSeku/modules/discovery/users/wpusers.py", line 20, in run
    users  = self.wpjson()
  File "/root/WPSeku/modules/discovery/users/wpusers.py", line 49, in wpjson
    json = loads(resp.content,encoding="utf-8")
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

**Comment by MAH69IK** [comment]
Hello! I have similar issue :(
I have fresh Debian 9.5 and install WPSeku as say in instruction (+ install python3-pip package):

> git clone https://github.com/m4ll0k/WPSeku.git wpseku
> cd wpseku
> pip3 install -r requirements.txt
> python3 wpseku.py

Then, I install WordPress 3.9.1 and run wpseku:
`# python3 wpseku.py --url http://wordpress.test/ --verbose`
(wordpress.test = 127.0.0.1 in /etc/hosts)

But after enumerating I have this error:
```
[ + ] Not found plugins with passive enumeration
[ i ] Enumerating users...
Traceback (most recent call last):
  File "wpseku.py", line 71, in 
    wpseku().main()
  File "wpseku.py", line 65, in main
    wpusers(self.url,None,self.kwargs).run()
  File "/usr/src/wpseku/modules/discovery/users/wpusers.py", line 20, in run
    users = self.wpjson()
  File "/usr/src/wpseku/modules/discovery/users/wpusers.py", line 50, in wpjson
    json = loads(resp.content,encoding="utf-8")
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

Version of WPSeku - 0.4.0, Python - 3.5.3
