### ISSUE TITLE
wpseku was not running for kali linux 2018.1

### ISSUE THREAD

**Issue by vagisom** [m4ll0k/WPSeku#44]
Traceback (most recent call last):
  File "wpseku.py", line 6, in <module>
    from modules.bruteforce.wpxmlrpc import *
  File "/root/Desktop/WPSeku/modules/bruteforce/wpxmlrpc.py", line 10, in <module>
    from lib.request import *
  File "/root/Desktop/WPSeku/lib/request.py", line 10, in <module>
    from lib.check import *
  File "/root/Desktop/WPSeku/lib/check.py", line 7, in <module>
    from urllib.parse import urlparse
ImportError: No module named parse

**Comment by vagisom** [comment]
if someone can solve this problem plz call me back

**Comment by m4ll0k** [comment]
Try with python v3: `python3 wpseku.py`

**Comment by sammashar56** [comment]
yah its still not working
