### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte

### ISSUE THREAD

**Issue by dnlwgnr89** [m4ll0k/WPSeku#45]
```
vagrant@ubuntu-xenial:~/wpseku$ python3 wpseku.py --scan /vagrant/remote/public_html/
...
[ i ] Scanning /vagrant/remote/public_html/wp-content/wflogs/attack-data.php file
Traceback (most recent call last):
  File "wpseku.py", line 71, in <module>
    wpseku().main()
  File "wpseku.py", line 54, in main
    Scan().run(self.scan)
  File "/home/vagrant/wpseku/lib/scan.py", line 59, in run
    self.testFile(file)
  File "/home/vagrant/wpseku/lib/scan.py", line 68, in testFile
    res += self.csrf(code)
  File "/home/vagrant/wpseku/lib/scan.py", line 92, in csrf
    pattern = re.findall(b.decode("utf-8"),cd.decode("utf-8"),re.I)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8f in position 28: invalid start byte
```

This file (attack-data.php) is a binary file, so of course it fails to be decoded - is there any option do an exclude on type or regex name/path?

**Comment by dnlwgnr89** [comment]
For context, I'm running the scan locally on the server via SSHFS

**Comment by dnlwgnr89** [comment]
Fixed and added pull request #46
